# Generated by Django 3.0.6 on 2020-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('avatar_s', models.ImageField(upload_to='static/avatar', verbose_name='用户头像(小)')),
                ('avatar_m', models.ImageField(upload_to='static/avatar', verbose_name='用户头像(中)')),
                ('avatar_l', models.ImageField(upload_to='static/avatar', verbose_name='用户头像(大)')),
            ],
        ),
    ]
