# Generated by Django 3.0.6 on 2020-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_l',
            field=models.ImageField(height_field=200, upload_to='static/avatar', verbose_name='用户头像(大)', width_field=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_m',
            field=models.ImageField(height_field=100, upload_to='static/avatar', verbose_name='用户头像(中)', width_field=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_s',
            field=models.ImageField(height_field=30, upload_to='static/avatar', verbose_name='用户头像(小)', width_field=30),
        ),
    ]
