# Generated by Django 3.0.6 on 2020-07-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200713_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_l',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_m',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_s',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=123, max_length=128, verbose_name='用户头像'),
            preserve_default=False,
        ),
    ]
